version: '3.7'

services:
  trim_video_db:
    image: mongo:latest
    container_name: trim_video_db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
